### ISSUE TITLE
Feature request: Documentation support

### ISSUE THREAD

**Issue by saona-raimundo** [bnjjj/witgen#3]
Thanks for the crate!

I wanted to ask if there could be documentation support.

[Wit supports only comments](https://github.com/bytecodealliance/wit-bindgen/blob/main/WIT.md#comments) and does not differentiate between documentation and code comments. But, when using [`wit-bindgen`](https://github.com/bytecodealliance/wit-bindgen) to transform to markdown, comments are part of the generated `.md` and correctly located.

## Proposal 

I propose to make use of this to pass over documentation comments in Rust as comments (using `\\`) to the generated `.wit` file.
Code comments in the Rust file would be ignored.

## Use case

At the end of the day, the objective is to generate the `.wit` file that people possibly outside of the Rust world can use, therefore it makes sense to me to generate the documentation also outside of the Rust world.

I do not have experience in this type of macros, but I could do the research if needed.

**Comment by bnjjj** [comment]
I'm not sure to understand what you mean by using `\\` but you're right I definitely should take comments written in Rust code for a `witgen` tagged element.

**Comment by saona-raimundo** [comment]
Thank you for the quick answer!

And sorry I meant `//` (comments). 
I was asking for formalizing the support of doc-comments (`///`) which are already functional in bytecodealliance/wit-bindgen#117. So maybe one could use simply `///` in the generated `wit` file(?)

**Comment by bnjjj** [comment]
Oh yes indeed. I will try to implement this and generate `///` in the wit generated files. I won't have enough time to do this this week but next week should be ok :)

**Comment by bnjjj** [comment]
Documentation has been added in this commit https://github.com/bnjjj/witgen/commit/896328beb6427d7fb840a03b1446fdafbdbb3ad6 and is now available in the `0.4.0` version published on crates.io

Thanks for the feature request ! Let me know if anything is missing
