### ISSUE TITLE
[Bug] version mismatch

### ISSUE THREAD

**Issue by willemneal** [bnjjj/witgen#31]
In the last update `cargo_witgen`, didn't update the dependency to the newest version.

https://github.com/bnjjj/witgen/blob/c5fd2e98119dd8bf26b85d1d1c86c1e16b7b8a6d/crates/cargo_witgen/Cargo.toml#L22

I think perhaps it's finally time to invest in a GH action to handle the versioning and publishing.

**Comment by bnjjj** [comment]
I can't agree more ! I just didn't find time to do this
