### ISSUE TITLE
Add default, world or interface block around wit definitions

### ISSUE THREAD

**Issue by reenigneEsrever92** [bnjjj/witgen#37]
The generated wit files result in an error when trying to use them with (some!?) other tools. Especially those coming from the bytecode alliance (wasmtime, wit-bindgen, etc.). I guess current generated wit files would work with wai-bindgen and others. 

I'm not quite sure why. My guess is that declaring one of `default`, `world` or `interface` as a top-level declaration was not mandatory before.

Do you want to change the implementation so that one of these top level declarations will be present in the generated output?

If so how would the implementation actually look? Would all Rust declarations that are annotated with only the witgen macro automatically be added to the "default" interface + the ability to pass in a world and / or interface the declaration should belong to?

**Comment by willemneal** [comment]
#36 is tracking updating to the newest version of wit. 

I'm not really sure how it will work yet, but my guess is that we would add arguments to the witgen macro. 

If you have any ideas of how you would like to use it please share. I hope to get to this next week.

**Comment by reenigneEsrever92** [comment]
Yes, no. I think passing arguments to the macro is totally fine. Being half way (or quarter way) familiar with the wit spec, that would be totally understandable to me and be somewhat what I would have expected.
