### ISSUE TITLE
[bug/question] cargo add doesn't work

### ISSUE THREAD

**Issue by willemneal** [bnjjj/witgen#6]
https://github.com/bnjjj/witgen/blob/411e1c0c534adb7973619d211b02b8492d4716fc/README.md?plain=1#L28

```
cargo add --help
```

returns
```bash
error: no such subcommand: `add`

        Did you mean `d`?
```

Version:
```
cargo 1.58.0 (7f08ace4f 2021-11-24)
```

Is this a subcommand you have to install?

**Comment by bnjjj** [comment]
Yes you have to install cargo-edit. cargo install cargo-edit

**Comment by willemneal** [comment]
Ah great!  I've been wanting that for some time!
