### ISSUE TITLE
[Feature] Add version of witgen to generated comment

### ISSUE THREAD

**Issue by willemneal** [bnjjj/witgen#9]
Currently this comment is at the top of the final generated wit file.  This line could also indicate which version of witgen was used to produce the file.

>`// This is a generated file by witgen (https://github.com/bnjjj/witgen), please do not edit yourself, you can generate a new one thanks to cargo witgen generate command`

**Comment by bnjjj** [comment]
Yes indeed ! It's a good idea. Will do it :)

**Comment by willemneal** [comment]
fixed by #10
